[package]
name = "pkg-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
pingora = { workspace = true, features = ["proxy"] }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
