[package]
name = "pkg-scheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
pkg-types = { path = "../types" }
tracing = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
